### ISSUE TITLE
Wrong keys shown

### ISSUE THREAD

**Issue by highend** [LastLifeLeft/Inputify#11]
Windows Server 2019, region is set to Germany.

The operating system language is english, no language pack installed.

My keyboards have a US ANSI layout.

The keyboard setting (in the OS) is: US

01. Pressing e.g. the `'` key (with shift it would be `"`) leads Inputify to display `"` and not `'` as expected
The same happens with a few other keys as well, e.g. `;` = `:`, the backtick shows `~`

02. The usage of the escape key isn't shown at all via Inputify

**Comment by LastLifeLeft** [comment]
1. I used the Microsoft list of key codes : https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes. You can see that ' and " share the same key code, so does ; and : or ` and ~. In those situations where I had to choose, I selected the character that matched both my keyboard and a US keyboard. Note that Inputify doesn't display the character you typed but the button you pressed : it should not be expected to display something different depending on any key combination.
2. I don't even know how I managed to miss it, since it's in my original list of button. Also forgot Tab and CAPS. This will be fixed in the next version, thanks for noticing! ♥

**Comment by highend** [comment]
> Note that Inputify doesn't display the character you typed but the button you pressed

The button is labelled e.g. `;`. And the above char (printed on it) is `:`. So Inputify should display the `;` when the key is pressed but it shows `:` instead...
