### ISSUE TITLE
Portable mode

### ISSUE THREAD

**Issue by highend** [LastLifeLeft/Inputify#5]
Please add a portable mode.

Either by allowing us to specify the path to `Preference.ini` in the options (if left empty the file is stored in the current working folder of Inputify) or by just checking if the file is already there and then use it (a valid way if we copy it over from `%APPDATA%\❤x1\Inputify` and then delete that folder

Nice app btw!

**Comment by LastLifeLeft** [comment]
@highend Could you test this and confirm if it's the behavior you are looking for? https://github.com/LastLifeLeft/Inputify/blob/Portable-Attempt/Inputify.exe
If it finds a `Preference.ini` file in the same folder as the executable, it'll use it. Otherwise, it'll resume normal behavior.

(I'm not a native English speaker, and I misinterpret stuff from time to time, so I'm making sure)

**Comment by highend** [comment]
@LastLifeLeft 

That version works, it takes the `Preference.ini` file if it's in the same directory as the .exe (and it doesn't try to recreate the folder under `%APPDATA%`). But... At the moment, it won't write any changes back to this .ini file again. So if you change a setting, it will be lost after quitting Inputify.
